services:
  web:
    image: ghcr.io/buddying-inc/webserver-amzn2:apache24-php81
    platform: linux/amd64
    container_name: bear-web
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ../source/app
        target: /var/www/html
        read_only: false
        consistency: delegated
      - type: bind
        source: localhost.conf
        target: /etc/httpd/conf.d/00_localhost.conf
        read_only: true
      - type: bind
        source: opcache-disable.ini
        target: /etc/opt/remi/php81/php.d/opcache-disable.ini
        read_only: true
    ports:
      - "80:80"
    environment:
      - PHP_XDEBUG=on
      - COMPOSER_ALLOW_SUPERUSER=1

  memcached:
    image: memcached
    container_name: bear-memcached
    ports:
      - "11211:11211"
